% =========================================================================
% LineKml - Write a simple KML LineString trajectory.
%
% DESCRIPTION:
%   Writes a KML document containing a single LineString (track) using
%   longitude, latitude, and altitude samples. The caller is responsible for
%   opening and closing the file handle.
%
% USAGE:
%   fid = fopen('trajectory.kml','w');
%   LineKml(fid, 'Trajectory', lat, lon, h);
%   fclose(fid);
%
% INPUTS:
%   fileID   : File identifier from fopen().
%   fileName : Track name shown in Google Earth.
%   wei      : Latitude array (decimal degrees).
%   jing     : Longitude array (decimal degrees).
%   z        : Altitude array (meters).
%
% NOTES:
%   - KML uses coordinates in the order: lon,lat,alt.
%
% =========================================================================

function [] = LineKml(fileID, fileName, wei, jing, z)
fprintf(fileID,['<?xml version="1.0" encoding="UTF-8"?>' ...
    '<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">' ...
    '<Document>' ...
    '<name>',fileName,'</name>' ...
    '<Style id="sn_ylw-pushpin">' ...
    '<LineStyle>' ...
    '<color>ff0000ff</color>' ...
    '<width>2</width>' ...
    '</LineStyle>' ...
    '<PolyStyle>' ...
    '<fill>0</fill>' ...
    '</PolyStyle>' ...
    '</Style>' ...
    '<Style id="sn_ylw-pushpin0">' ...
    '<LineStyle>'...
    '<color>ff0000ff</color>'...
    '<width>2</width>'...
    '</LineStyle>'...
    '<PolyStyle>'...
    '<fill>0</fill>'...
    '</PolyStyle>'...
    '</Style>'...
    '<Placemark>'...
    '<name>',fileName,'</name>'...
    '<description></description>'...
    '<styleUrl>#sn_ylw-pushpin</styleUrl>'...
    '<LineString>'...
    '<tessellate>1</tessellate>'...
    '<coordinates>']);

for i = 1:length(wei)
    weidu = wei(i);
    jingdu = jing(i);
    gaocheng = z(i);
    fprintf(fileID,'%.10f,%.10f,%.10f\n', jingdu, weidu, gaocheng);
end

fprintf(fileID,['</coordinates>\n' ...
    '</LineString>\n' ...
    '</Placemark>\n'...
    '</Document>\n'...
    '</kml>\n']);

end